# Generated by Django 4.0.4 on 2024-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nominee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
