# Generated by Django 4.0.4 on 2024-04-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nominee_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
