# Generated by Django 4.0.4 on 2024-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nominee_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
