# Generated by Django 4.0.4 on 2024-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_nominee_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.CharField(blank=True, max_length=305, null=True),
        ),
    ]
