# Generated by Django 4.0.4 on 2024-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.AddField(
            model_name='nominee',
            name='poll',
            field=models.ManyToManyField(to='core.poll'),
        ),
    ]
