# Generated by Django 4.0.4 on 2024-04-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_nominee_company_remove_poll_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='name_of_voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poll'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
