# Generated by Django 4.0.4 on 2024-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vote_name_of_voter_vote_poll_vote_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='nominee_position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_start',
            field=models.DateField(null=True),
        ),
    ]
