# Generated by Django 4.0.4 on 2024-04-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_nominee_nominee_position_poll_vote_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='month',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='vote_count',
        ),
    ]
