# Generated by Django 4.0.4 on 2024-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_nominee_poll_nominee_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='nominees',
            field=models.JSONField(null=True),
        ),
    ]
