# Generated by Django 4.0.4 on 2024-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_poll_nominees'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
