# Generated by Django 4.0.4 on 2024-04-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_employee_alter_vote_choice_delete_nominee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
