# Generated by Django 4.0.4 on 2024-04-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
