# Generated by Django 4.0.4 on 2024-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
